### ISSUE TITLE
mpicbg library has incompatible licensing

### ISSUE THREAD

**Issue by ctrueden** [bogovicj/jitk-tps#7]
This library is licensed APLv2, but depends on mpicbg, which is licensed as GPLv2 only. As such, this library is in practice GPLv2 only also. Furthermore, the imglib2-algorithm library is ostensibly licensed BSD-2 but depends on jitk-tps, so it is also GPLv2 in practice.

@axtimwalde @bogovicj What should we do to resolve this?

See also [this thread on the ImageJ forum](http://forum.imagej.net/t/eliminate-or-reduce-the-gpl-portion-of-imglib2/4418).

**Comment by bogovicj** [comment]
Hmm, what is trakem2's license? It depends on mpicbg, eh?

Removing the dep to mpicbg is possible, and we can move all functionality that depends on into trakem2 - then we can leave the license as is.

I'm also happy to change the license.  @ctrueden, do you have a preference?

John

**Comment by ctrueden** [comment]
In general, my preference is permissive over GPL. In this specific case, I think imglib2-algorithm needs to stay BSD-2, which means it either A) needs to stop depending on jitk-tps; or B) jitk-tps needs to be legitimately permissively licensed.

> Removing the dep to mpicbg is possible, and we can move all functionality that depends on into trakem2 - then we can leave the license as is.

That sounds like a workable solution to me. Sorry to make more work for you, but it is important to have our ducks in a row with this stuff.

**Comment by bogovicj** [comment]
Started on this [here](https://github.com/saalfeldlab/jitk-tps/tree/tpsRmMpicbg).
Will need to check downstream stuff, but shouldn't be too bad.

**Comment by bogovicj** [comment]
The changes above affected BigWarp; [this branch](https://github.com/saalfeldlab/bigwarp/tree/tpsRmMpicbg) addresses the issues that came up.

imglib2-realtransform is not affected.

Fortunately, TrakEm2 is also not affected:  As far as I know, nothing else treated TPS's as `CoordinateTransforms`, but if there is something, it will need to depend TrakEM2, and use [this class](https://github.com/trakem2/TrakEM2/blob/b82d1274ec0d060bacd3c433394a67322a434366/trakem2-transform/src/main/java/mpicbg/trakem2/transform/ThinPlateSplineTransform.java) which wraps a TPS.

**Comment by ctrueden** [comment]
@bogovicj Thanks very much for taking care of this. Let me know if there is any action you need from me. Once you are ready, I can cut releases etc. if that helps.

**Comment by bogovicj** [comment]
No problem @ctrueden, thanks for offering to help.
I should some time later to double check and test my changes, and will post back when all looks good.

**Comment by bogovicj** [comment]
@ctrueden , 
Sorry was slow.  Got sidetracked, then wanted to fix some other stuff before a new release.

Changes are merged, and Bigwarp's master now works with the new, proper, jitk-tps.
[Bigwarp does currently depend on a SNAPSHOT version of jitk-tps](https://github.com/saalfeldlab/bigwarp/blob/master/pom.xml#L134) in order to build correctly.  Of course, this can go away once the version of jitk-tps in pom-scijava is updated.

If you wouldn't mind double-checking my work then working your magic re: updating poms and cutting releases, I'd appreciate it very much.  No rush from my end.

Thanks again for the heads up about this!  :slightly_smiling_face:

**Comment by ctrueden** [comment]
> Changes are merged, and Bigwarp's master now works with the new, proper, jitk-tps.

Thank you very much.

> Bigwarp does currently depend on a SNAPSHOT version of jitk-tps in order to build correctly.

It is important that all commits in master's history use release dependencies only. When multiple components are intertwined, the correct way to do this is to develop on a topic branch with SNAPSHOT coupling(s), then once you are certain things are good, cut the upstream release(s), then rebase the topic branch to depend on the new release(s) throughout its history. Otherwise, you end up with a master branch that is not bisectable because it contains irreproducible builds at some commits. See [this wiki page](http://imagej.net/Architecture#How_SciJava_achieves_reproducible_builds) for further details.

> If you wouldn't mind double-checking my work then working your magic re: updating poms and cutting releases, I'd appreciate it very much.

* Released `jitk-tps` version 3.0.0. It had to be a major version bump because the public API changed in a backwards-incompatible manner.
* Released `bigwarp` version 3.0.1. There were no API changes to that component, so a patch release there is fine just to update the dependency version of jitk-tps.
* Released `imglib2-realtransform` version 2.0.0-beta-38. Also no API changes—just a patch release to update the dependency version of `jitk-tps` for licensing reasons.
* Released `imglib2-algorithm` version 0.8.1. Also no API changes—just a patch release to update the dependency versions of `imglib2-realtransform` and `jitk-tps` for licensing reasons.
* Did not release a new `imglib2-algorithm-fft` version, because surprisingly, `imglib2-algorithm-fft` does not depend on `imglib2-algorithm` except for test scope.
* Updated `pom-scijava` to reference these new releases (https://github.com/scijava/pom-scijava/commit/ef9ee51ee08301da07b91d9d4c445ee7cb3ef24d).
* Did not yet release a `pom-scijava` version 17.0.0, since it is not urgent, but things are now set such that the next POM update will iron out this dependency licensing issue.

Thanks again for your diligence, @bogovicj.
